using Lage.EnumDescription.Generators.Extensions;
using Lage.EnumDescription.Generators.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace Lage.EnumDescription.Generators.Generator
{
    internal class ClassFileBuilder
    {
        private readonly StringBuilder sb;
        private readonly TargetInfo info;
        private readonly string classFullName;
        private int indent = 0;

        public ClassFileBuilder(TargetInfo info)
        {
            this.info = info;
            this.classFullName = info.GetFullName();
            this.sb = new StringBuilder(512);

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();
            indent++;
            sb.AppendXmlBlock(indent,
                "<summary>",
                "为<see cref=\"{{item.TypeName}}\"/>常量枚举提供高性能的扩展方法和元数据。",
                "</summary>",
                "<remarks>",
                "为避免运行时反射而生成，此类提供常量枚举值、本地化描述和字符串名称之间的高效转换，以及只读查找表。",
                "</remarks>");
            sb.IndentLine(indent, $"{info.Accessibility.ToName()} partial class {info.TypeName}");
            sb.IndentLine(indent, $"{{");
            indent++;
        }

        public ClassFileBuilder AppendToDescription()
        {
            sb.IndentLine(indent, $"public static string ToDescription(string? enumName,string? defaultValue = null) => enumName switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Name}\" => \"{item.Description}\",");
            }
            sb.IndentLine(indent, $"_ => defaultValue");
            indent--;
            sb.IndentLine(indent, $"}};");
            return this;
        }

        public ClassFileBuilder AppendParseByDescription()
        {
            sb.IndentLine(indent, $"public static string ToDescription(string? enumName,string? defaultValue = null) => enumName switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Name}\" => \"{item.Description}\",");
            }
            sb.IndentLine(indent, $"_ => defaultValue");
            indent--;
            sb.IndentLine(indent, $"}};");
            return this;
        }

        public string Build()
        {
            indent--;
            sb.IndentLine(indent, "}");
            indent--;
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
