using Lage.EnumDescription.Generators.CoreModels;
using Lage.EnumDescription.Generators.Extensions;
using Lage.EnumDescription.Generators.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace Lage.EnumDescription.Generators.Generator
{
    internal class EnumFileBuilder
    {
        private readonly StringBuilder sb;
        private readonly TargetInfo info;
        private readonly string fullName;
        private int indent = 1;

        public EnumFileBuilder(TargetInfo info) 
        {
            sb = new StringBuilder(512);
            this.info = info;
            fullName = info.GetFullName();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();
            indent++;
            sb.AppendXmlBlock(indent,
                "<summary>",
                "为<see cref=\"{{item.TypeName}}\"/>枚举提供高性能的扩展方法和元数据。",
                "</summary>",
                "<remarks>",
                "为避免运行时反射而生成，此类提供枚举值、本地化描述和字符串名称之间的高效转换，以及只读查找表。",
                "</remarks>");
            sb.IndentLine(indent, $"{info.Accessibility.ToName()} static class {info.TypeName}Extensions");
            sb.IndentLine(indent, $"{{");
        }

        public EnumFileBuilder AppendToDescription()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
                "<summary>",
                "将指定的枚举值转换为其本地化描述字符串。",
                "</summary>",
                "<param name=\"value\">",
                "要转换的枚举值。",
                "</param>",
                "<param name=\"defaultValue\">",
                "如果<paramref name=\"value\"/>与任何已定义的枚举成员都不匹配，则返回此值。",
                "默认为<see langword=\"null\"/>。",
                "</param>",
                "<returns>",
                "如果找到匹配项，则返回与枚举成员关联的描述文本；",
                "否则返回指定的<paramref name=\"defaultValue\"/>。",
                "</returns>",
                "<remarks>",
                "此扩展方法提供了一种类型安全且高效的方式，用于检索枚举值的可读标签。",
                "如果输入值未定义（例如，强制转换为整数但没有对应的成员），则安全地返回<paramref name=\"defaultValue\"/>，而不是抛出异常或返回数字字符串。",
                "</remarks>");
            sb.IndentLine(indent, $"public static string ToDescription(this {info.GetFullName()} value,string? defaultValue = null) => value switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"{info.GetFullName()}.{item.Name} => \"{item.Description}\",");
            }
            sb.IndentLine(indent, $"_ => defaultValue");
            indent--;
            sb.IndentLine(indent, $"}};");
            return this;
        }

        public EnumFileBuilder AppendSource()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
                "<summary>",
                "只读数据源",
                "</summary>");
            sb.IndentLine(indent, $"public static readonly {MappingEntry.FullNamWithGlobal}<{fullName}>[] Source = new {MappingEntry.FullNamWithGlobal}<{fullName}>[]");
            sb.IndentLine(indent, "{");
            indent++;
            for (int i = 0; i < info.MemberInfos.Length; i++)
            {
                var member = info.MemberInfos[i];

                if (info.MemberInfos.Length - 1 == i)
                    sb.IndentLine(indent, $"{MappingEntry.CreateEnumMapping(fullName, member.Name, member.Description)}");
                else
                    sb.IndentLine(indent, $"{MappingEntry.CreateEnumMapping(fullName, member.Name, member.Description)},");
            }
            sb.IndentLine(indent, "};");
            indent--;
            return this;
        }

        public EnumFileBuilder AppendToName()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
            "<summary>",
            "将指定的枚举值转换为其对应的成员名称字符串。",
            "</summary>",
            "<param name=\"value\">",
            "要转换的枚举值。",
            "</param>",
            "<param name=\"defaultValue\">",
            "如果<paramref name=\"value\"/>与任何已定义的枚举成员都不匹配，则返回此值。",
            "默认为<see langword=\"null\"/>。",
            "</param>",
            "<returns>",
            "如果找到匹配项，则返回枚举成员的名称；",
            "否则返回指定的<paramref name=\"defaultValue\"/>。",
            "</returns>",
            "<remarks>",
            "如果输入值未定义（例如，由于强制转换为整数但没有对应的枚举成员），则返回<paramref name=\"defaultValue\"/>，而不是抛出异常或返回数字字符串表示。",
            "匹配基于精确的枚举成员定义。",
            "</remarks>");

            sb.IndentLine(indent, $"public static string ToName(this {fullName} value,string? defaultValue = null) => value switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"{fullName}.{item.Name} => \"{item.Name}\",");
            }
            sb.IndentLine(indent, $"_ => defaultValue");
            indent--;
            sb.IndentLine(indent, $"}};");

            return this;
        }

        public EnumFileBuilder AppendParseByName()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
            "<summary>",
            "将指定的字符串表示形式解析为对应的枚举值。",
            "</summary>",
            "<param name=\"enumStr\">",
            "枚举成员名称的字符串表示形式（区分大小写）。",
            "</param>",
            "<returns>",
            "如果<paramref name=\"enumStr\"/>与已定义的成员匹配，则返回解析后的枚举值。",
            "</returns>",
            "<exception cref=\"ArgumentException\">",
            "当<paramref name=\"enumStr\"/>与任何已定义的枚举成员名称都不匹配时抛出。",
            "异常消息包含无效的输入字符串。",
            "</exception>",
            "<remarks>",
            "此方法在失败时抛出异常，而不是返回<see langword=\"false\"/>。",
            "</remarks>");

            sb.IndentLine(indent, $"public static {fullName} Parse(string enumStr)");
            sb.IndentLine(indent, $"{{");
            indent++;
            sb.IndentLine(indent, $"return enumStr switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Name}\" => {fullName}.{item.Name},");
            }
            sb.IndentLine(indent, $"_ => throw new {TypesConst.ArgumentException}($\"The value '{{enumStr}}' is not a valid member of {{typeof({fullName}).Name}}.\", nameof(enumStr))");
            indent--;
            sb.IndentLine(indent, $"}};");
            indent--;
            sb.IndentLine(indent, $"}}");

            return this;
        }

        public EnumFileBuilder AppendTryParseByName()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
         "<summary>",
         "尝试将指定的字符串表示形式解析为对应的枚举值。",
         "</summary>",
         "<param name=\"enumStr\">",
         "枚举成员名称的字符串表示形式（区分大小写）。",
         "</param>",
         "<param name=\"target\">",
         "当此方法返回<see langword=\"true\"/>时，包含解析后的枚举值；",
         "否则为<see langword=\"null\"/>。",
         "</param>",
         "<returns>",
         "如果<paramref name=\"enumStr\"/>转换成功，则为<see langword=\"true\"/>；",
         "否则为<see langword=\"false\"/>。",
         "</returns>");

            sb.IndentLine(indent, $"public static bool TryParseByName(string enumStr, {TypesConst.NotNullWhenTrue} out {fullName}? target)");
            sb.IndentLine(indent, $"{{");
            indent++;
            sb.IndentLine(indent, $"target = enumStr switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Name}\" => {fullName}.{item.Name},");
            }
            sb.IndentLine(indent, $"_ => ({fullName}?)null");
            indent--;
            sb.IndentLine(indent, $"}};");

            sb.IndentLine(indent, $"return target != null;");
            indent--;
            sb.IndentLine(indent, $"}}");
            return this;
        }

        public EnumFileBuilder AppendTryParseByDescription()
        {

            sb.AppendLine();
            sb.AppendXmlBlock(indent,
            "<summary>",
            "尝试将指定的描述字符串解析为对应的枚举值。",
            "</summary>",
            "<param name=\"desc\">",
            "与枚举成员关联的本地化描述文本（区分大小写）。",
            "</param>",
            "<param name=\"target\">",
            "当此方法返回<see langword=\"true\"/>时，包含解析后的枚举值；",
            "否则为<see langword=\"null\"/>。",
            "</param>",
            "<returns>",
            "如果<paramref name=\"desc\"/>成功匹配已定义的描述，则为<see langword=\"true\"/>；",
            "否则为<see langword=\"false\"/>。",
            "</returns>");
            sb.IndentLine(indent, $"public static bool TryParseByDescription(string desc, {TypesConst.NotNullWhenTrue} out {fullName}? target)");
            sb.IndentLine(indent, $"{{");
            indent++;
            sb.IndentLine(indent, $"target = desc switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Description}\" => {fullName}.{item.Name},");
            }
            sb.IndentLine(indent, $"_ => ({fullName}?)null");
            sb.IndentLine(indent, $"}};");
            indent--;
            sb.IndentLine(indent, $"return target != null;");
            indent--;
            sb.IndentLine(indent, $"}}");
            return this;
        }

        public string Build()
        {
            sb.IndentLine(indent, "}");
            indent--;
            sb.IndentLine(indent, "}");
            return sb.ToString();
        }
    }
}
