using Lage.EnumDescription.Generators.CoreModels;
using Lage.EnumDescription.Generators.Extensions;
using Lage.EnumDescription.Generators.Models;
using System.Text;

namespace Lage.EnumDescription.Generators.Builders
{
    internal class ClassFileBuilder
    {
        private readonly StringBuilder sb;
        private readonly TargetInfo info;
        private readonly string classFullName;
        private int indent = 0;

        public ClassFileBuilder(TargetInfo info)
        {
            this.info = info;
            this.classFullName = info.GetFullName();
            this.sb = new StringBuilder(512);

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine();

            foreach (var parentClass in info.ParentClass)
            {
                indent++;
                sb.IndentLine(indent, $"{parentClass.Accessibility.ToName()} partial class {parentClass.Name}");
                sb.IndentLine(indent, "{");
            }

            indent++;
            sb.AppendXmlBlock(indent,
                "<summary>",
                "为<see cref=\"{{item.TypeName}}\"/>常量枚举提供高性能的扩展方法和元数据。",
                "</summary>",
                "<remarks>",
                "为避免运行时反射而生成，此类提供常量枚举值、本地化描述和字符串名称之间的高效转换，以及只读查找表。",
                "</remarks>");
            sb.IndentLine(indent, $"{info.Accessibility.ToName()} partial class {info.TypeName}");
            sb.IndentLine(indent, $"{{");
            indent++;
        }

        public ClassFileBuilder AppendToDescription()
        {
            sb.IndentLine(indent, $"public static string ToDescription(string? enumName,string? defaultValue = null) => enumName switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Name}\" => \"{item.Description}\",");
            }
            sb.IndentLine(indent, $"_ => defaultValue");
            indent--;
            sb.IndentLine(indent, $"}};");
            return this;
        }

        public ClassFileBuilder AppendGeneratedSource()
        {
            sb.AppendLine();
            sb.AppendXmlBlock(indent,
                "<summary>",
                "只读数据源",
                "</summary>");
            sb.IndentLine(indent, $"public static readonly {MappingEntry.FullNamWithGlobal}<string>[] GeneratedSource = new {MappingEntry.FullNamWithGlobal}<string>[]");
            sb.IndentLine(indent, "{");
            indent++;
            for (int i = 0; i < info.MemberInfos.Length; i++)
            {
                var member = info.MemberInfos[i];

                if (info.MemberInfos.Length - 1 == i)
                    sb.IndentLine(indent, $"{MappingEntry.CreateStringMapping(member.Name, member.Name, member.Description)}");
                else
                    sb.IndentLine(indent, $"{MappingEntry.CreateStringMapping(member.Name, member.Name, member.Description)},");
            }

            indent--;
            sb.IndentLine(indent, "};");
            return this;
        }

        public ClassFileBuilder AppendTryParseByDescription()
        {

            sb.AppendLine();
            sb.AppendXmlBlock(indent,
            "<summary>",
            "尝试将指定的描述字符串解析为对应的枚举值。",
            "</summary>",
            "<param name=\"desc\">",
            "与枚举成员关联的本地化描述文本（区分大小写）。",
            "</param>",
            "<param name=\"target\">",
            "当此方法返回<see langword=\"true\"/>时，包含解析后的枚举值；",
            "否则为<see langword=\"null\"/>。",
            "</param>",
            "<returns>",
            "如果<paramref name=\"desc\"/>成功匹配已定义的描述，则为<see langword=\"true\"/>；",
            "否则为<see langword=\"false\"/>。",
            "</returns>");
            sb.IndentLine(indent, $"public static bool TryParseByDescription(string desc, {TypesConst.NotNullWhenTrue} out string? target)");
            sb.IndentLine(indent, $"{{");
            indent++;
            sb.IndentLine(indent, $"target = desc switch");
            sb.IndentLine(indent, $"{{");
            indent++;
            foreach (var item in info.MemberInfos)
            {
                sb.IndentLine(indent, $"\"{item.Description}\" => \"{item.Name}\",");
            }
            sb.IndentLine(indent, $"_ => null");

            indent--;
            sb.IndentLine(indent, $"}};");
            sb.IndentLine(indent, $"return target != null;");
            indent--;
            sb.IndentLine(indent, $"}}");
            return this;
        }

        public string Build()
        {
            foreach (var parentClass in info.ParentClass)
            {
                indent--;
                sb.IndentLine(indent, "}");
            }

            indent--;
            sb.IndentLine(indent, "}");
            indent--;
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
